apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"matrix-discovery"},"name":"matrix-discovery","namespace":"caritas"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"matrix-discovery"}},"template":{"metadata":{"labels":{"app":"matrix-discovery"}},"spec":{"containers":[{"image":"nginx:alpine","name":"discovery","ports":[{"containerPort":8090,"name":"http-discovery"}],"volumeMounts":[{"mountPath":"/etc/nginx/conf.d/default.conf","name":"discovery-config","subPath":"default.conf"},{"mountPath":"/usr/share/nginx/html/.well-known/matrix/server/caritas.local","name":"discovery-data","subPath":"caritas.local"},{"mountPath":"/usr/share/nginx/html/.well-known/matrix/server/caritas2.local","name":"discovery-data","subPath":"caritas2.local"}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"volumes":[{"configMap":{"name":"matrix-discovery-config"},"name":"discovery-config"},{"configMap":{"name":"matrix-discovery-data"},"name":"discovery-data"}]}}}}
  creationTimestamp: "2025-10-19T17:35:11Z"
  generation: 1
  labels:
    app: matrix-discovery
  name: matrix-discovery
  namespace: caritas
  resourceVersion: "734325"
  uid: af40ac99-fc0d-4ff5-9cd1-63881402c80e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: matrix-discovery
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: matrix-discovery
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: discovery
        ports:
        - containerPort: 8090
          name: http-discovery
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: discovery-config
          subPath: default.conf
        - mountPath: /usr/share/nginx/html/.well-known/matrix/server/caritas.local
          name: discovery-data
          subPath: caritas.local
        - mountPath: /usr/share/nginx/html/.well-known/matrix/server/caritas2.local
          name: discovery-data
          subPath: caritas2.local
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: matrix-discovery-config
        name: discovery-config
      - configMap:
          defaultMode: 420
          name: matrix-discovery-data
        name: discovery-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-19T17:35:11Z"
    lastUpdateTime: "2025-10-19T17:35:42Z"
    message: ReplicaSet "matrix-discovery-7648fc4c78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-27T23:40:35Z"
    lastUpdateTime: "2025-10-27T23:40:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
